# config/meta.yml
meta_product_name: "MetroVert"
meta_title: "MetroVert - Mon compagnon de potager"
meta_description: "L’application incontournable pour les débutants du potager en ville !"
meta_image: "open-graph-banner.png" # should exist in `app/assets/images/`
twitter_account: "@metrovert" # required for Twitter Cards
