 # config/meta.yml
 meta_product_name: "MetroVert"
 meta_title: "MetroVert une application incontournable pour les débutants du potager en ville !"
 meta_description: "Une application incontournable pour les débutants du potager en ville !"
 meta_image: "/home/alizee/code/Alizee441/MetroVert/app/assets/images/logo.png" # should exist in `app/assets/images/`
 twitter_account: "@product_twitter_account" # required for Twitter Cards
